language: python
fast_finish: true

python:
  - 3.6

os:
  - linux

group: travis_latest


git:
  depth: 3

addons:
  apt:
    packages:
      - gfortran
      - liblapack-dev
      - libatlas-base-dev

before_install:
  # this is temporary for pip < 9.1
  - pip -q install numpy

install: pip -q install -e .[tests]

before_script:
   - cd bin
   - cmake ..
   - make 
   - cd ..

script: coverage run tests/Test.py -v

after_success: coveralls

