language: python

python:
    - 3.5

sudo: false

notifications:
  email: false

git:
  depth: 1

env:
    - FC=/usr/bin/gfortran-4.9

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gfortran-4.9

before_install:
    - mkdir -p "$HOME/.local/bin"
    - ln -fs /usr/bin/gfortran-4.9 "$HOME/.local/bin/gfortran" && gfortran --version
    - ln -fs /usr/lib/gcc/x86_64-linux-gnu/4.9/libgfortran.so $HOME/miniconda/lib/libgfortran.so.3
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH=$HOME/miniconda/bin:$PATH

install:
    - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION
    - source activate test
    - pip -q install coveralls
    - conda install --yes --quiet numpy
    - python setup.py develop

script:
    - coverage run test/test.py

after_success:
    - coveralls
